### ISSUE TITLE
ERR! 404

### ISSUE THREAD

**Issue by misteltein** [textlint-ja/textlint-rule-no-duplicated-bunmatsu-hyougen#1]
> npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@textlint-ja%2ftextlint-rule-no-duplicated-bunmatsu-hyougen - Not found
npm ERR! 404 
npm ERR! 404  '@textlint-ja/textlint-rule-no-duplicated-bunmatsu-hyougen@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2019-04-16T15_48_38_341Z-debug.log

お世話になっております．
npm install textlint-rule-no-duplicated-bunmatsu-hyougen
してみたところ上記のようなエラーが出ました．(npm@6.9.0, node@v11.14.0)
npm registry から外されているのでしょうか？
よくわからないです．

**Comment by azu** [comment]
作ったはいいけど、イマイチな出来だったので公開まではしてなかったやつっぽいですね(記憶が曖昧)

**Comment by azu** [comment]
https://github.com/textlint-ja/textlint-rule-no-duplicated-bunmatsu-hyougen/releases/tag/0.1.0

とりあえず 0.1.0 としてnpmに公開しておきました。

**Comment by misteltein** [comment]
ありがとうございます。
